### ISSUE TITLE
Detail_Friends Page draft

### ISSUE THREAD

**Issue by overthename** [wanted-pj/wanted_app#6]
1.
![image](https://user-images.githubusercontent.com/80188940/139862171-78a933bc-2700-4764-a804-2ad572368abe.png)

여기 버튼 클릭시 MainFragment->**ShowFriendsFragment**로 이동

2. 
상세친구페이지(ShowFriendsFragment) xml :  framgent_show_Friends.xml

3. 
상세친구페이지(ShowFriendsFragment) Adater : Detail_FriendAdapter
상세친구페이지(ShowFriendsFragment) Data class : Detail_Friend
상세친구페이지(ShowFriendsFragment) Data class xml : item_detail_friend

디자인 수정부탁함돠

**Comment by hyun-seung** [comment]
지금 그게 설정이 안 되어있네
위에 삼각형은 커뮤니티로 빠지는건데, 아래 기능은 여기서 보여주는게 끝이라서 더 이어지는 세부 페이지 설정이 필요하겠다!

**Comment by overthename** [comment]
그걸 상세친구페이지로 만든건데....?

> 지금 그게 설정이 안 되어있네 위에 삼각형은 커뮤니티로 빠지는건데, 아래 기능은 여기서 보여주는게 끝이라서 더 이어지는 세부 페이지 설정이 필요하겠다!

**Comment by Seon-Ju** [comment]
![image](https://user-images.githubusercontent.com/48851230/140272282-6d9d3ba7-9bb5-4866-ace5-cf735363d4b0.png)
arrow에 연결되어 있던 기능을 사용자가 받아들이기 쉽게 RecyclerView 안에 Footer를 추가해서 더보기로 뺐고, Footer에 클릭이벤트 설정해서 상세페이지로 연결되게 만들어뒀습니다.

**Comment by Seon-Ju** [comment]
Friend와 관련된 파일들은 한번에 정렬돼서 보여지면 찾기 편할 것 같아서 이름을 바꿨어요.

상세친구페이지 : (전) ShowFriendsFragment → (후) FriendMoreFragment
상세친구페이지 xml : (전) framgent_show_Friends → (후) fragment_friend_more
상세친구페이지 Adater : (전) Detail_FriendAdapter → (후) FriendMoreAdapter
상세친구페이지 Data class : (전) Detail_Friend → (후) 삭제하고 Friend 클래스 재사용
상세친구페이지 item xml : (전) item_detail_friend → (후) item_friend_more

홈탭에서 보이는 친구 레이아웃과 관련된 파일은 Friend/friend로 시작하고,
상세친구페이지와 관련된 파일은 FriendMore/friend_more로 시작합니다.
